@Craftify.Api_HostAddress = https://localhost:7283

POST {{Craftify.Api_HostAddress}}/api/Authentication/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "password": "P@ssw0rd"
}


###

